vich_uploader:
    db_driver: orm

    mappings:
        fruit_image:
            uri_prefix: /pictures/fruits
            upload_destination: '%kernel.project_dir%/public/pictures/fruits'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        legume_image:
            uri_prefix: /pictures/legumes
            upload_destination: '%kernel.project_dir%/public/pictures/legumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        abonnement_image:
            uri_prefix: /pictures/abonnements
            upload_destination: '%kernel.project_dir%/public/pictures/abonnements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        option_image:
            uri_prefix: /pictures/options
            upload_destination: '%kernel.project_dir%/public/pictures/options'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
